--- 
masterConnection: "root@172.17.0.2" # A typical Docker connection
standardConnection: "root@172.17.0.2"
output_dir: output
staging_deploy_root: CHANGEME
production_deploy_root: CHANGEME
## CHANGE THIS WHEN WE RELEASE A VERSION:
release_version: "3.2"
r_version_associated_with_release: "3.2.2"
## CHANGE THIS WHEN WE RELEASE A VERSION:
devel_version: "3.3"
## CHANGE THIS WHEN WE ADD A VERSION:
## this is the list of all versions for which we want to generate "new" bioc-views, package
## index, and package detail pages
versions:
## if old versions (no older than 2.5) need to be rebuilt for any reason,
## add them here, but in most cases this should just contain the
## release and devel versions (though after a release you should
## let the no-longer-release version build one last time so package
## landing pages won't say "release version"):
- "3.2"
- "3.3"
## CHANGE THIS as various parts of the new devel version become available.
## set to "[]" if none are available.
devel_repos:
- "bioc"
- "data/experiment"
- "data/annotation"
## CHANGE this when the build machines change:
## also, don't include machines that are not building yet (comment them out)
active_devel_builders:
  linux: "CHANGEME"
  windows: "CHANGEME"
  mac_mavericks: "CHANGEME"
active_release_builders:
  linux: "CHANGEME"
  windows: "CHANGEME"
  mac_snowleopard: "CHANGEME"
  mac_mavericks: "CHANGEME"

## CHANGE this when the workflow builder builds
## on a newer version of bioc
workflow_builder:
  bioc_version: "3.2"
  r_version: "3.2"

## CHANGE this when the single package builder builds
## on a newer version of bioc
single_package_builder:
  bioc_version: "3.1"
  r_version: "3.2"

rss_hub_url: "CHANGEME"
## CHANGE these as AMI IDS change
ami_ids:
 bioc2_8: ami-3a2ef452
 bioc2_9: ami-2623f94e
 bioc2_10: ami-5621fb3e
 bioc2_11: ami-f827fd90
 bioc2_12: ami-7224fe1a
 bioc2_13: ami-4a25ff22
 bioc2_14: ami-9c25fff4
 bioc3_0: ami-be7917d6
 bioc3_1: ami-a3d126c8
 bioc3_2: ami-85d88de0
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_unified
  encoding: utf-8
  config:
    encoding: utf-8
- items_root: /mailing-list-posts
  type: biostar_list
  encoding: utf-8
  config:
    gmane_rss_url: 'CHANGEME'
    cache_file: tmp/gmane_list_cache_file.yaml
    encoding: utf-8
    ttl: 10
- items_root: /help/bioc-views/package-pages
  layouts_root: /
  type: bioc_views
  encoding: utf-8
  config:
    json_dir: "assets/packages/json"
    encoding: utf-8
- items_root: /help/publications/papers/pubmed
  type: pubmed_papers
  encoding: utf-8
  config:
    cache_file: tmp/pubmed_cache_file.yaml
    retmax: 20
    ttl: 24
    baseurl: CHANGEME
#   queried database, e.g. "pubmed" or "pmc"; can be a vector
    db: [pubmed, pmc]
    term: bioconductor
#   Sorting of query results. This one is database-specific; possible values include
#   pubmed: pub+date, first+author, last+author, journal, title, relevance
#   pmc: print+pub+date, electronic+pub+date, journal, pmc+live+date
#   For default sorting leave this field out
    sort: [ "", electronic+pub+date]
# CHANGE THIS when it becomes apparent which future versions of BioC will
# work with which versions of R:
r_ver_for_bioc_ver: 
  "1.6": "2.1"
  "1.7": "2.2"
  "1.8": "2.3"
  "1.9": "2.4"
  "2.0": "2.5"
  "2.1": "2.6"
  "2.2": "2.7"
  "2.3": "2.8"
  "2.4": "2.9"
  "2.5": "2.10"
  "2.6": "2.11"
  "2.7": "2.12"
  "2.8": "2.13"
  "2.9": "2.14"
  "2.10": "2.15"
  "2.11": "2.15" # R switching to yearly releases, BioC remaining the same
  "2.12": "3.0"
  "2.13": "3.0"
  "2.14": "3.1"
  "3.0": "3.1"
  "3.1": "3.2"
  "3.2": "3.2"
  "3.3": "3.3"
  "3.4": "3.3"
  "3.5": "3.4"
# UPDATE THIS when we release a version
release_dates: # old info from http://en.wikipedia.org/wiki/Bioconductor#Milestones
  "1.0": "1/5/2001"
  "1.1": "11/19/2002"
  "1.2": "5/29/2003"
  "1.3": "10/30/2003"
  "1.4": "5/17/2004"
  "1.5": "10/25/2004"
  "1.6": "5/18/2005"
  "1.7": "10/14/2005"
  "1.8": "4/27/2006"
  "1.9": "10/4/2006"
  "2.0": "4/26/2007"
  "2.1": "10/8/2007"
  "2.2": "5/1/2008"
  "2.3": "10/22/2008"
  "2.4": "4/21/2009"
  "2.5": "10/28/2009"
  "2.6": "4/23/2010"
  "2.7": "10/18/2010"
  "2.8": "4/14/2011"
  "2.9": "11/1/2011"
  "2.10": "4/2/2012"
  "2.11": "10/3/2012"
  "2.12": "4/4/2013"
  "2.13": "10/15/2013"
  "2.14": "4/14/2014"
  "3.0": "10/14/2014"
  "3.1": "4/17/2015"
  "3.2": "10/14/2015"
mirrors:
 - 0-Bioconductor:
   - institution: Bioconductor, automatic redirection to servers worldwide
     institution_url: CHANGEME
     contact: Bioconductor Maintainer
     contact_email: CHANGEME
     city: World-wide
     mirror_url: http://bioconductor.org/
     https_mirror_url: https://bioconductor.org/
     country_code: us
 - United States:
   - institution: CHANGEME
     institution_url: CHANGEME
     contact: CHANGEME
     mirror_url: CHANGEME
     contact_email: CHANGEME
     city: CHANGEME
     country_code: us
